---
- name: Include OS-specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: Install common apt packages
  apt: pkg={{ item }} state=latest
  with_items:
    - python-apt
    - python-pycurl
    - python-pip
    - git-core
  sudo: yes

- name: Install Java
  include: java.yml

- name: Install Elasticsearch
  include: elasticsearch.yml